#!/usr/bin/env bash
#This scipt will print "Best School" 8 times then print "Hi" in the 9th time

count=0
while [ $count -lt 10 ]
do
	echo "Best School"
	if [ $count -eq 8 ]
	then
		echo "Hi"
	fi
	(( count++ ))
done
